/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeka;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author RIZQY
 */
public class main2 extends javax.swing.JFrame {
    
    
    Connection conn;
    private DefaultTableModel model;
    
    
    /**
     * Creates new form main2
     */
    public main2() {
        initComponents();
        
        conn = Koneksi.getConnection();
        
        model = new DefaultTableModel();
        table.setModel(model);
    

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Hobi");
    model.addColumn("Umur");

    loadData();
    
    }
    
    
    private void loadData() {
      model.setRowCount(0);

      try {
          String sql = "SELECT * FROM manusia";
          PreparedStatement ps = conn.prepareStatement(sql);//menyiapkan query 
          ResultSet rs = ps.executeQuery();//menyimpan data
          while (rs.next()) {
             // Menambahkan baris ke dalam model tabel
             model.addRow(new Object[]{
             rs.getInt("id"),
             rs.getString("nama"),
             rs.getString("hobi"),
             rs.getString("umur"),
            
           });
          }
      } catch (SQLException e) {
         System.out.println("Error Save Data" + e.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Hobi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama_T1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        id_T1 = new javax.swing.JTextField();
        lihat_T1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_saran = new javax.swing.JTextArea();
        hobi_T1 = new javax.swing.JTextField();
        umur_T1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Masukan Hobi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bola", "Badminton", "Futsal", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel1.add(jComboBox3, gridBagConstraints);

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 257, 154));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeka/begroundtab (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 480));

        jTabbedPane2.addTab("Hobi", jPanel4);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nama");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 37, -1));

        Hobi.setText("Hobi");
        jPanel3.add(Hobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 37, -1));

        jLabel10.setText("Umur");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 43, -1));
        jPanel3.add(nama_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 259, -1));

        jLabel1.setText("Lihat list Peogram Latihhan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 178, 160, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nama ", "hobi", "umur"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 490, 129));

        jLabel4.setText("id");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 37, -1));

        id_T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_T1ActionPerformed(evt);
            }
        });
        jPanel3.add(id_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 259, -1));

        lihat_T1.setText("Lihat");
        lihat_T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat_T1ActionPerformed(evt);
            }
        });
        jPanel3.add(lihat_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 175, -1, -1));

        edit.setText("tambah");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        save.setText("edit");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jButton6.setText("hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel11.setText("saran program latihan");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        tbl_saran.setColumns(20);
        tbl_saran.setRows(5);
        jScrollPane2.setViewportView(tbl_saran);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 483, -1));

        hobi_T1.setEditable(false);
        hobi_T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_T1ActionPerformed(evt);
            }
        });
        jPanel3.add(hobi_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 259, -1));
        jPanel3.add(umur_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 259, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeka/begroundtab (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 490));

        jTabbedPane2.addTab("tab1", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setText("program latihan sport badminton, futsal, bola");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel8)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (jComboBox3.getSelectedIndex()){
            case 0:
                hobi_T1.setText("Bola");
                break;
            case 1:
                hobi_T1.setText("Badminton");
                break;
            default :
                hobi_T1.setText("Futsal");
                break;          
        }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lihat_T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat_T1ActionPerformed
    if(hobi_T1.getText().equals("Bola")){
        tbl_saran.setText("Tujuan: Meningkatkan kontrol bola, akurasi tendangan, dan kelincahan.\n" +
                            "\n" + "Dribbling: Latihan menggiring bola di ruang kecil. Gunakan kursi atau botol sebagai rintangan.\n" +
                            "Passing: Latih tendangan ke tembok dengan target tertentu untuk meningkatkan akurasi.\n" +
                            "Ball Control: Latihan juggling bola untuk melatih kontrol dan keseimbangan.\n" +
                            "Latihan Stamina: Lari di tempat atau lompat tali selama 10-15 menit.");
    }
    if(hobi_T1.getText().equals("Badminton")){
        tbl_saran.setText("Shadow Badminton: Latihan footwork dan pukulan (forehand, backhand, smash, dropshot) tanpa shuttlecock.\n" +
                            "Durasi: 10-15 menit.\n"+"Latihan Footwork\n" + "Ladder Drill: Gerakan cepat melangkah ke dalam dan keluar pola tangga di lantai.\n" +
                            "Lunges: Langkah besar ke depan, kembali ke posisi awal.\n" + "Durasi: 3 set x 1 menit.\n"+"Pantulkan Bola Tenis: Lemparkan bola ke dinding dan tangkap secepat mungkin.\n" +
                            "Durasi: 10-15 menit.");    
    }
    if(hobi_T1.getText().equals("Futsal")){
        tbl_saran.setText("Tujuan: Meningkatkan ketepatan dan fleksibilitas permainan (disarankan umur 12 sampai 30).\n" +"\n" +
                        "Quick Footwork: Latih gerakan kaki cepat dengan ladder drill atau menggambar pola di lantai (disarankan 20-30 tahun).\n" +
                        "Passing dan Shooting: Gunakan dinding sebagai rekan passing. Tambahkan target untuk shooting(disarankan umur 10-20).\n" +
                        "Wall Control Drill: Tendang bola ke dinding dan kontrol kembali menggunakan bagian dalam kaki(disarankan umur 10-20 tahun.");
        
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_lihat_T1ActionPerformed

    private void id_T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_T1ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
if (nama_T1.getText().isEmpty() || 
        hobi_T1.getText().isEmpty() ||
            umur_T1.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, 
            "Harap isi dulu!", 
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
        try {
        // Cek apakah Tf_durasi berisi angka
        int umr = Integer.parseInt(umur_T1.getText());
        
        
        String sql = "INSERT INTO manusia (nama, hobi, umur) VALUES (?,?,?)";
        PreparedStatement ps = conn.prepareStatement(sql);
//        ps.setInt(1, id);
        ps.setString(1, nama_T1.getText());
        ps.setString(2, hobi_T1.getText()); // Menggunakan setInt untuk kolom durasi_pengerjaan
        ps.setInt(3, umr);
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        loadData();
        
//        loadComboBoxProyek();
        } catch (NumberFormatException e) {
            // Menampilkan pesan jika tahun tidak valid
            JOptionPane.showMessageDialog(this, "Tahun harus berupa angka.", "Input Error", JOptionPane.ERROR_MESSAGE);

        }
        
        catch (SQLException e) {
            System.out.println("Error Save Data: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    if (id_T1.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, 
            "Harap isi id dulu!", 
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        return;
        }
        if (table.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "THERE IS NO DATA", "DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
            }else{
            try {
          String sql = "UPDATE manusia SET nama = ?, hobi = ?, umur = ? WHERE id = ?";
          PreparedStatement ps = conn.prepareStatement(sql);
          ps.setString(1, nama_T1.getText());
          ps.setString(2, hobi_T1.getText());
          String umrrr = umur_T1.getText().isEmpty() ? "umur tidak di ketahui" : umur_T1.getText();
          ps.setString(3, umrrr);
          
          ps.setInt(4,Integer.parseInt(id_T1.getText()));
          ps.executeUpdate();
          JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
          loadData();
      }  catch (SQLException e) {
          System.out.println("Error Save Data" + e.getMessage());
    }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    if (id_T1.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, 
            "Harap isi id dulu!", 
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }else
        try  {
            String sql = "DELETE FROM manusia WHERE id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(id_T1.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData();
        } catch (SQLException e) {
            System.out.println("Error Save Data" + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void hobi_T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hobi_T1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hobi;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hobi_T1;
    private javax.swing.JTextField id_T1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton lihat_T1;
    private javax.swing.JTextField nama_T1;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JTextArea tbl_saran;
    private javax.swing.JTextField umur_T1;
    // End of variables declaration//GEN-END:variables

    private void updateData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
